// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVRBewrakkAF4No7qhieSduLlVatNbVY',
    appId: '1:575040263056:web:749df68a2b1ddadf0e5915',
    messagingSenderId: '575040263056',
    projectId: 'rebuy-b1940',
    authDomain: 'rebuy-b1940.firebaseapp.com',
    storageBucket: 'rebuy-b1940.firebasestorage.app',
    measurementId: 'G-ZVJCCCXM1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT7AGu8jiPHsbM5GeP9ra3i3Er0RAS5qQ',
    appId: '1:575040263056:android:8ec09a651225c9e30e5915',
    messagingSenderId: '575040263056',
    projectId: 'rebuy-b1940',
    storageBucket: 'rebuy-b1940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0YEuwLBIKkNMI9JyrvcGoCMQOp5KxjkE',
    appId: '1:575040263056:ios:53985c3b39693a580e5915',
    messagingSenderId: '575040263056',
    projectId: 'rebuy-b1940',
    storageBucket: 'rebuy-b1940.firebasestorage.app',
    iosBundleId: 'com.example.rebuyy',
  );
}
